CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	DisplayOrder INT
);


CREATE TABLE Statuses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	ColorHex NVARCHAR(10)
);


CREATE TABLE Units(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL
);


CREATE TABLE ShoppingItems(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(200),
	Amount DECIMAL(10,2),
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id),
	StatusId INT FOREIGN KEY REFERENCES Statuses(Id),
	UnitId INT FOREIGN KEY REFERENCES Units(Id)
);
